package opuscc

import (
	"testing"
	"unsafe"

	libc "github.com/kazzmir/opus-go/libcshim"
)

func TestAmp2Log2LocalUnion(t *testing.T) {
	mode := OpusT_OpusCustomMode{FnbEBands: 3}
	bandE := []OpusT_celt_ener{0.75, 1.5, 3.25, 0.625, 2.25, 4.5}
	bandLogE := make([]OpusT_celt_glog, len(bandE))

	Opus_amp2Log2(nil, uintptr(unsafe.Pointer(&mode)), 2, 3, uintptr(unsafe.Pointer(&bandE[0])), uintptr(unsafe.Pointer(&bandLogE[0])), 2)

	want := []OpusT_celt_glog{-6.8525376, -5.6650376, -14, -7.115572, -5.0800753, -14}
	for i, expected := range want {
		if got := bandLogE[i]; got != expected {
			t.Fatalf("bandLogE[%d]: got %v, want %v", i, got, expected)
		}
	}
}

func TestQuantCoarseEnergyLocalQI(t *testing.T) {
	tls := libc.NewTLS()
	defer tls.Close()

	mode := OpusT_OpusCustomMode{FnbEBands: 3}
	eBands := [6]OpusT_celt_glog{1.3, -0.8, 2.1, 0.4, 1.8, -1.2}
	oldEBands := [6]OpusT_celt_glog{0.1, -0.5, 1.4, 0.3, 1.1, -0.9}
	errors := [6]OpusT_celt_glog{}
	buffer := make([]byte, 32)
	var encoder OpusT_ec_enc
	Opus_ec_enc_init(tls, uintptr(unsafe.Pointer(&encoder)), entropyBufferPointer(buffer), uint32(len(buffer)))

	badness := quant_coarse_energy_impl(
		tls,
		uintptr(unsafe.Pointer(&mode)),
		0,
		3,
		uintptr(unsafe.Pointer(&eBands[0])),
		uintptr(unsafe.Pointer(&oldEBands[0])),
		120,
		0,
		uintptr(unsafe.Pointer(&e_prob_model[0][0][0])),
		uintptr(unsafe.Pointer(&errors[0])),
		uintptr(unsafe.Pointer(&encoder)),
		2,
		0,
		0,
		16,
		0,
	)
	Opus_ec_enc_done(tls, uintptr(unsafe.Pointer(&encoder)))

	if got, want := badness, int32(0); got != want {
		t.Fatalf("badness: got %d, want %d", got, want)
	}
	if got, want := oldEBands, [6]OpusT_celt_glog{1.0898438, -0.36923218, 2.337799, 0.26953125, 1.9882812, -0.7286072}; got != want {
		t.Fatalf("reconstructed energies: got %v, want %v", got, want)
	}
	if got, want := errors, [6]OpusT_celt_glog{0.2101562, -0.43076783, -0.23779917, 0.13046876, -0.1882813, -0.47139287}; got != want {
		t.Fatalf("quantization errors: got %v, want %v", got, want)
	}
	if got, want := buffer[:encoder.Foffs], []byte{0x69, 0x06}; string(got) != string(want) {
		t.Fatalf("encoded bytes: got % x, want % x", got, want)
	}
	if got, want := encoder.Fnbits_total, int32(41); got != want {
		t.Fatalf("encoded bit count: got %d, want %d", got, want)
	}
}

/* Expected values generated by /tmp/opencode/qce_ref.c, which links
 * ../opus/.libs/libopus.a and calls the C quant_coarse_energy with the same
 * inputs (fake mode with nbEBands=3, C=2, start=0, end=3, effEnd=3,
 * 32-byte buffer). */
func TestQuantCoarseEnergyWrapperCReference(t *testing.T) {
	tls := libc.NewTLS()
	defer tls.Close()
	pseudostack := libc.Xmalloc(tls, 16)
	scratch := libc.Xmalloc(tls, GLOBAL_STACK_SIZE)
	*(*OpusT_opus_ccgo_pseudostack_state)(unsafe.Pointer(pseudostack)) = OpusT_opus_ccgo_pseudostack_state{
		Fscratch_ptr:  scratch,
		Fglobal_stack: scratch,
	}
	libc.Xpthread_setspecific(tls, 0x6f707573, pseudostack)

	mode := OpusT_OpusCustomMode{FFs: 48000, FnbEBands: 3}

	type scenario struct {
		name          string
		eBands        [6]OpusT_celt_glog
		oldEBands     [6]OpusT_celt_glog
		LM            int32
		budget        OpusT_opus_uint32
		nbAvailable   int32
		forceIntra    int32
		delayedIntra  OpusT_opus_val32
		twoPass       int32
		lossRate      int32
		lfe           int32
		wantOldEBands [6]OpusT_celt_glog
		wantError     [6]OpusT_celt_glog
		wantDelayed   OpusT_opus_val32
		wantBuf       string
		wantNbits     int32
	}

	scenarios := []scenario{
		{
			name:          "forced intra",
			eBands:        [6]OpusT_celt_glog{1.3, -0.8, 2.1, 0.4, 1.8, -1.2},
			oldEBands:     [6]OpusT_celt_glog{0.1, -0.5, 1.4, 0.3, 1.1, -0.9},
			budget:        120,
			nbAvailable:   16,
			forceIntra:    1,
			delayedIntra:  1.0,
			wantOldEBands: [6]OpusT_celt_glog{1, -1.1499939, 2.1499939, 0, 2, -1.29998779},
			wantError:     [6]OpusT_celt_glog{0.299999952, 0.349993944, -0.0499939919, 0.400000006, -0.200000048, 0.0999877453},
			wantDelayed:   2.60999966,
			wantBuf:       "\xe7\x9e\x6e\x40",
			wantNbits:     57,
		},
		{
			name:          "two-pass, non-intra wins",
			eBands:        [6]OpusT_celt_glog{1.4, -0.7, 2.0, 0.5, 1.7, -1.1},
			oldEBands:     [6]OpusT_celt_glog{1.3, -0.8, 2.1, 0.4, 1.8, -1.2},
			budget:        45,
			nbAvailable:   16,
			delayedIntra:  0.25,
			twoPass:       1,
			wantOldEBands: [6]OpusT_celt_glog{1.16796875, -0.71875, 1.88671863, 0.359375, 1.6171875, -1.078125},
			wantError:     [6]OpusT_celt_glog{0.232031226, 0.0187500119, 0.113281369, 0.140625, 0.0828125477, -0.0218750238},
			wantDelayed:   0.261797458,
			wantBuf:       "\x00\x00",
			wantNbits:     41,
		},
		{
			name:          "two-pass, intra wins (encoder state restored)",
			eBands:        [6]OpusT_celt_glog{-0.3, 0.2, -0.1, 0.4, -0.2, 0.3},
			oldEBands:     [6]OpusT_celt_glog{-9, -8, -9.5, -8.2, -9.7, -8.4},
			budget:        45,
			nbAvailable:   16,
			delayedIntra:  0.25,
			twoPass:       1,
			lossRate:      10,
			wantOldEBands: [6]OpusT_celt_glog{0, 0, 0, 0, 0, 0},
			wantError:     [6]OpusT_celt_glog{-0.300000012, 0.200000003, -0.100000001, 0.400000006, -0.200000003, 0.300000012},
			wantDelayed:   200,
			wantBuf:       "\xe0\x00\x00",
			wantNbits:     49,
		},
		{
			name:          "auto intra via delayedIntra threshold",
			eBands:        [6]OpusT_celt_glog{1.4, -0.7, 2.0, 0.5, 1.7, -1.1},
			oldEBands:     [6]OpusT_celt_glog{1.3, -0.8, 2.1, 0.4, 1.8, -1.2},
			budget:        120,
			nbAvailable:   16,
			delayedIntra:  13.0,
			wantOldEBands: [6]OpusT_celt_glog{1, -1.1499939, 2.1499939, 1, 1.8500061, -1.29998779},
			wantError:     [6]OpusT_celt_glog{0.399999976, 0.449993849, -0.149993896, -0.5, -0.150006056, 0.199987888},
			wantDelayed:   0.0599999726,
			wantBuf:       "\xe8\xb9\xdc",
			wantNbits:     49,
		},
		{
			name:          "budget clamp disables intra and two-pass",
			eBands:        [6]OpusT_celt_glog{1.4, -0.7, 2.0, 0.5, 1.7, -1.1},
			oldEBands:     [6]OpusT_celt_glog{1.3, -0.8, 2.1, 0.4, 1.8, -1.2},
			budget:        2,
			nbAvailable:   16,
			forceIntra:    1,
			delayedIntra:  0.25,
			twoPass:       1,
			wantOldEBands: [6]OpusT_celt_glog{1.16796875, -1.71875, 0.806732059, -0.640625, 0.537200928, -2.23809814},
			wantError:     [6]OpusT_celt_glog{0.232031226, 1.01874995, 1.19326794, 1.140625, 1.16279912, 1.13809812},
			wantDelayed:   0.261797458,
			wantBuf:       "\x00",
			wantNbits:     33,
		},
		{
			name:          "lfe with LM=1 forced intra",
			eBands:        [6]OpusT_celt_glog{1.3, -0.8, 2.1, 0.4, 1.8, -1.2},
			oldEBands:     [6]OpusT_celt_glog{0.1, -0.5, 1.4, 0.3, 1.1, -0.9},
			LM:            1,
			budget:        120,
			nbAvailable:   16,
			forceIntra:    1,
			delayedIntra:  1.0,
			lfe:           1,
			wantOldEBands: [6]OpusT_celt_glog{1, -1.1499939, -0.850006104, 0, 2, -1.29998779},
			wantError:     [6]OpusT_celt_glog{0.299999952, 0.349993944, 2.95000601, 0.400000006, -0.200000048, 0.0999877453},
			wantDelayed:   2.60999966,
			wantBuf:       "\xe7\x98\x98",
			wantNbits:     49,
		},
	}

	for _, s := range scenarios {
		eBands, oldEBands, errors := s.eBands, s.oldEBands, [6]OpusT_celt_glog{}
		buffer := make([]byte, 32)
		var encoder OpusT_ec_enc
		Opus_ec_enc_init(tls, uintptr(unsafe.Pointer(&encoder)), entropyBufferPointer(buffer), 32)
		delayedIntra := s.delayedIntra
		Opus_quant_coarse_energy(tls, uintptr(unsafe.Pointer(&mode)), 0, 3, 3,
			uintptr(unsafe.Pointer(&eBands[0])), uintptr(unsafe.Pointer(&oldEBands[0])),
			s.budget, uintptr(unsafe.Pointer(&errors[0])), uintptr(unsafe.Pointer(&encoder)),
			2, s.LM, s.nbAvailable, s.forceIntra, uintptr(unsafe.Pointer(&delayedIntra)),
			s.twoPass, s.lossRate, s.lfe)
		Opus_ec_enc_done(tls, uintptr(unsafe.Pointer(&encoder)))

		if got := oldEBands; got != s.wantOldEBands {
			t.Errorf("%s: oldEBands: got %v, want %v", s.name, got, s.wantOldEBands)
		}
		if got := errors; got != s.wantError {
			t.Errorf("%s: error: got %v, want %v", s.name, got, s.wantError)
		}
		if got, want := delayedIntra, s.wantDelayed; got != want {
			t.Errorf("%s: delayedIntra: got %v, want %v", s.name, got, want)
		}
		if got, want := string(buffer[:encoder.Foffs]), s.wantBuf; got != want {
			t.Errorf("%s: encoded bytes: got % x, want % x", s.name, got, want)
		}
		if got, want := encoder.Fnbits_total, s.wantNbits; got != want {
			t.Errorf("%s: encoded bit count: got %d, want %d", s.name, got, want)
		}
	}
}
