package opuscc

import (
	"testing"
	"unsafe"

	libc "github.com/kazzmir/opus-go/libcshim"
)

/* Expected values generated by /tmp/opencode/qab_ref.c linked against the
 * no-intrinsics C build /tmp/opencode/opusni/libopusni.a (same celt sources
 * and config.h as ../opus/.libs/libopus.a but with the OPUS_X86_* intrinsics
 * undefined). The stock .libs build presumes SSE2 on x86-64, so alg_quant
 * dispatches to op_pvq_search_sse2 there: different SIMD summation order
 * (and no in-place abs of X), which changes PVQ decisions and therefore the
 * encoded bytes. The Go port is a translation of the plain-C paths, so the
 * no-intrinsics build is the matching reference; against it every scenario
 * below is bit-exact, including X/Y float bits.
 *
 * Fake mode: Fs=48000, 3 bands of 4 bins each (eBands {0,4,8,12}), LM=0,
 * logN {2,2,2}; cache index row for LM=0 at positions 3..5; band 1 has a low
 * pulse-cache cap so it splits; pulses {84,80,76} frac-bits, total 400,
 * balance 24, codedBands 3, 64-byte ec buffers.
 *
 * All memory whose address crosses the transpiled API is Xmalloc'd: a
 * uintptr conversion launders escape analysis, so Go stack locals stay on
 * the goroutine stack and a mid-call stack growth (the PVQ recursion is
 * deep enough to trigger one) leaves the callee writing through a stale
 * address. This corrupted the theta_rdo scenario before the buffers were
 * pinned (encoder state ended up clobbered while the in-function view was
 * fine). */
func xmallocArray[T any](tls *libc.TLS, n int) []T {
	return unsafe.Slice((*T)(unsafe.Pointer(libc.Xmalloc(tls, uint64(n*int(unsafe.Sizeof(*new(T))))))), n)
}

func TestQuantAllBandsCReference(t *testing.T) {
	tls := libc.NewTLS()
	defer tls.Close()
	pseudostack := libc.Xmalloc(tls, 16)
	scratch := libc.Xmalloc(tls, GLOBAL_STACK_SIZE)
	*(*OpusT_opus_ccgo_pseudostack_state)(unsafe.Pointer(pseudostack)) = OpusT_opus_ccgo_pseudostack_state{
		Fscratch_ptr:  scratch,
		Fglobal_stack: scratch,
	}
	libc.Xpthread_setspecific(tls, 0x6f707573, pseudostack)

	eBandsTab := xmallocArray[int16](tls, 4)
	copy(eBandsTab, []int16{0, 4, 8, 12})
	logNTab := xmallocArray[int16](tls, 3)
	copy(logNTab, []int16{2, 2, 2})
	cacheIndex := xmallocArray[int16](tls, 6)
	copy(cacheIndex, []int16{0, 0, 0, 0, 9, 16})
	cacheBits := xmallocArray[uint8](tls, 21)
	copy(cacheBits, []uint8{
		8, 20, 30, 40, 48, 56, 64, 72, 80,
		6, 4, 8, 12, 16, 20, 24,
		4, 32, 56, 76, 96,
	})
	mode := xmallocArray[OpusT_OpusCustomMode](tls, 1)
	mode[0] = OpusT_OpusCustomMode{
		FFs:        48000,
		FnbEBands:  3,
		FeffEBands: 3,
		FeBands:    uintptr(unsafe.Pointer(&eBandsTab[0])),
		FlogN:      uintptr(unsafe.Pointer(&logNTab[0])),
	}
	mode[0].Fcache.Findex = uintptr(unsafe.Pointer(&cacheIndex[0]))
	mode[0].Fcache.Fbits = uintptr(unsafe.Pointer(&cacheBits[0]))

	bandE := xmallocArray[OpusT_celt_ener](tls, 6)
	copy(bandE, []OpusT_celt_ener{1.5, 0.7, 2.2, 1.1, 0.9, 1.8})
	pulses := xmallocArray[int32](tls, 3)
	copy(pulses, []int32{84, 80, 76})
	tfRes := xmallocArray[int32](tls, 3)

	type qabWant struct {
		xfnv, yfnv uint32
		masks      string
		seed       uint32
		buf        string
		nbits      int32
	}
	runEncode := func(name string, stereo bool, complexity, dual, spread int32, seedIn uint32, exp qabWant) {
		X := xmallocArray[OpusT_celt_norm](tls, 12)
		copy(X, []OpusT_celt_norm{0.5, -0.3, 0.8, 0.2, -0.6, 0.4, 0.1, 0.7, -0.2, 0.6, -0.5, 0.3})
		Y := xmallocArray[OpusT_celt_norm](tls, 12)
		copy(Y, []OpusT_celt_norm{-0.2, 0.6, -0.4, 0.3, 0.1, -0.5, 0.8, -0.1, 0.4, -0.6, 0.2, -0.7})
		collapse := xmallocArray[uint8](tls, 6)
		buffer := xmallocArray[uint8](tls, 64)
		encoder := xmallocArray[OpusT_ec_enc](tls, 1)
		seed := xmallocArray[uint32](tls, 1)
		seed[0] = seedIn

		Opus_ec_enc_init(tls, uintptr(unsafe.Pointer(&encoder[0])), uintptr(unsafe.Pointer(&buffer[0])), 64)
		var yPtr uintptr
		if stereo {
			yPtr = uintptr(unsafe.Pointer(&Y[0]))
		}
		Opus_quant_all_bands(tls, 1, uintptr(unsafe.Pointer(&mode[0])), 0, 3,
			uintptr(unsafe.Pointer(&X[0])), yPtr, uintptr(unsafe.Pointer(&collapse[0])),
			uintptr(unsafe.Pointer(&bandE[0])), uintptr(unsafe.Pointer(&pulses[0])),
			0, spread, dual, 3, uintptr(unsafe.Pointer(&tfRes[0])),
			400, 24, uintptr(unsafe.Pointer(&encoder[0])), 0, 3,
			uintptr(unsafe.Pointer(&seed[0])), complexity, 0, 0)
		Opus_ec_enc_done(tls, uintptr(unsafe.Pointer(&encoder[0])))

		nmasks := 3
		if stereo {
			nmasks = 6
		}
		if got := fnv1aFloats(X); got != exp.xfnv {
			t.Errorf("%s: Xfnv: got %08x, want %08x", name, got, exp.xfnv)
		}
		if stereo {
			if got := fnv1aFloats(Y); got != exp.yfnv {
				t.Errorf("%s: Yfnv: got %08x, want %08x", name, got, exp.yfnv)
			}
		}
		if got := string(collapse[:nmasks]); got != exp.masks {
			t.Errorf("%s: collapse_masks: got % x, want % x", name, got, exp.masks)
		}
		if got := seed[0]; got != exp.seed {
			t.Errorf("%s: seed: got %d, want %d", name, got, exp.seed)
		}
		if got := string(buffer[:encoder[0].Foffs]); got != exp.buf {
			t.Errorf("%s: encoded bytes: got % x, want % x", name, got, exp.buf)
		}
		if got := encoder[0].Fnbits_total; got != exp.nbits {
			t.Errorf("%s: encoded bit count: got %d, want %d", name, got, exp.nbits)
		}
	}

	runEncode("stereo encode theta_rdo", true, 8, 0, SPREAD_NORMAL, 123456789,
		qabWant{0xba1de34d, 0xa91fb3cd, "\x01\x01\x01\x01\x01\x01", 123456789, "\xfb\x1c\x14\xc0", 59})
	runEncode("stereo encode no rdo light spread", true, 5, 0, SPREAD_LIGHT, 987654321,
		qabWant{0x73c07e4a, 0x29a287d1, "\x01\x01\x01\x01\x00\x00", 987654321, "\x7e\xfb\x67\x5a", 61})
	runEncode("stereo encode dual stereo", true, 5, 1, SPREAD_NORMAL, 555555555,
		qabWant{0xfd324584, 0xd2dd4616, "\x01\x01\x01\x01\x00\x00", 555555555, "\x49\xda\x3b\x7a", 61})
	runEncode("mono encode aggressive spread", false, 9, 0, SPREAD_AGGRESSIVE, 111111111,
		qabWant{0x585e6f84, 0, "\x01\x01\x01", 111111111, "\x40\xb9\x10\x70", 60})

	/* Decode pass over the theta_rdo packet (bytes embedded from the C
	   harness); must reproduce the encode resynth exactly. */
	{
		X := xmallocArray[OpusT_celt_norm](tls, 12)
		Y := xmallocArray[OpusT_celt_norm](tls, 12)
		libc.Xmemset(tls, uintptr(unsafe.Pointer(&X[0])), 0, 48)
		libc.Xmemset(tls, uintptr(unsafe.Pointer(&Y[0])), 0, 48)
		collapse := xmallocArray[uint8](tls, 6)
		buffer := xmallocArray[uint8](tls, 64)
		libc.Xmemset(tls, uintptr(unsafe.Pointer(&buffer[0])), 0, 64)
		/* Full E5 packet: 4 range-coded bytes at the front; the encoder's
		   ec_enc_done ORs the 2 leftover end-window bits into the last
		   byte (buf[63] = 0x02), and the decoder reads raw bits back from
		   the end of the buffer. ec_range_bytes() only reports offs (4),
		   so the trailing byte is easy to miss. */
		copy(buffer, []uint8{0xfb, 0x1c, 0x14, 0xc0})
		buffer[63] = 0x02
		decoder := xmallocArray[OpusT_ec_dec](tls, 1)
		seed := xmallocArray[uint32](tls, 1)
		seed[0] = 123456789
		/* The C reference's ALLOC scratch lands on fresh (zeroed) stack
		   pages; zero the pseudostack scratch the same way so uninitialized
		   reads (if any) agree on both sides. */
		libc.Xmemset(tls, scratch, 0, uint64(GLOBAL_STACK_SIZE))
		(*OpusT_opus_ccgo_pseudostack_state)(unsafe.Pointer(pseudostack)).Fglobal_stack = scratch

		Opus_ec_dec_init(tls, uintptr(unsafe.Pointer(&decoder[0])), uintptr(unsafe.Pointer(&buffer[0])), 64)
		Opus_quant_all_bands(tls, 0, uintptr(unsafe.Pointer(&mode[0])), 0, 3,
			uintptr(unsafe.Pointer(&X[0])), uintptr(unsafe.Pointer(&Y[0])),
			uintptr(unsafe.Pointer(&collapse[0])), uintptr(unsafe.Pointer(&bandE[0])),
			uintptr(unsafe.Pointer(&pulses[0])), 0, SPREAD_NORMAL, 0, 3,
			uintptr(unsafe.Pointer(&tfRes[0])), 400, 24, uintptr(unsafe.Pointer(&decoder[0])),
			0, 3, uintptr(unsafe.Pointer(&seed[0])), 8, 0, 0)

		if got, want := fnv1aFloats(X), uint32(0xba1de34d); got != want {
			t.Errorf("decode: Xfnv: got %08x, want %08x", got, want)
		}
		if got, want := fnv1aFloats(Y), uint32(0xa91fb3cd); got != want {
			t.Errorf("decode: Yfnv: got %08x, want %08x", got, want)
		}
		if got, want := string(collapse), string([]byte{1, 1, 1, 1, 1, 1}); got != want {
			t.Errorf("decode: collapse_masks: got % x, want % x", got, want)
		}
		if got, want := seed[0], uint32(123456789); got != want {
			t.Errorf("decode: seed: got %d, want %d", got, want)
		}
	}
}
