package opuscc

import (
	"bufio"
	"encoding/hex"
	"fmt"
	"os"
	"testing"
	"unsafe"

	libc "github.com/kazzmir/opus-go/libcshim"
)

func TestMultistreamDecodeNativeCReference(t *testing.T) {
	// SILK NB packets and all expectations are generated by the retained C
	// harness: silent coupled stream plus nonzero mono stream, reordered and
	// duplicated channels, and a muted channel. Both public wrappers exercise
	// the native multistream loop. See the generator's noisy-stream reproducer
	// and summary.txt for the separate pre-existing PCM mismatch.
	f, err := os.Open("testdata/multistream_decode_ref.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	tls := libc.NewTLS()
	defer tls.Close()
	mapping := libc.Xmalloc(tls, 5)
	defer libc.Xfree(tls, mapping)
	copy(unsafe.Slice((*byte)(unsafe.Pointer(mapping)), 5), []byte{2, 0, 1, 2, 255})
	dec, err := Opus_opus_multistream_decoder_create(tls, 48000, 5, 2, 1, mapping)
	if err != nil {
		t.Fatal(err)
	}
	defer Opus_opus_multistream_decoder_destroy(tls, dec)
	data := libc.Xmalloc(tls, 4000)
	defer libc.Xfree(tls, data)
	pcm := libc.Xmalloc(tls, 6400*5*4)
	defer libc.Xfree(tls, pcm)
	va := libc.Xmalloc(tls, uint64(unsafe.Sizeof(uintptr(0))))
	defer libc.Xfree(tls, va)
	rng := libc.Xmalloc(tls, 4)
	defer libc.Xfree(tls, rng)
	scanner := bufio.NewScanner(f)
	for line := 1; scanner.Scan(); line++ {
		var name, packet string
		var length, frame, fec, shortOut, wantRet int32
		var wantHash uint64
		var wantRange uint32
		if n, err := fmt.Sscanf(scanner.Text(), "%s %d %d %d %d %d %d %d %s", &name, &length, &frame, &fec, &shortOut, &wantRet, &wantHash, &wantRange, &packet); err != nil || n != 9 {
			t.Fatalf("line %d: %v", line, err)
		}
		input := uintptr(0)
		if packet != "-" {
			bytes, err := hex.DecodeString(packet)
			if err != nil {
				t.Fatal(err)
			}
			if len(bytes) != int(length) {
				t.Fatal("fixture length mismatch")
			}
			copy(unsafe.Slice((*byte)(unsafe.Pointer(data)), 4000), bytes)
			input = data
		}
		libc.Xmemset(tls, pcm, 0xa5, 6400*5*4)
		var ret int32
		if shortOut != 0 {
			ret = Opus_opus_multistream_decode(tls, dec, input, length, pcm, frame, fec)
		} else {
			ret = Opus_opus_multistream_decode_float(tls, dec, input, length, pcm, frame, fec)
		}
		if ret != wantRet {
			t.Fatalf("%s line %d: return %d, want %d", name, line, ret, wantRet)
		}
		hash := uint64(14695981039346656037)
		if ret > 0 {
			width := 4
			if shortOut != 0 {
				width = 2
			}
			for _, b := range unsafe.Slice((*byte)(unsafe.Pointer(pcm)), int(ret)*5*width) {
				hash ^= uint64(b)
				hash *= 1099511628211
			}
		}
		if hash != wantHash {
			t.Fatalf("%s line %d: PCM hash %d, want %d", name, line, hash, wantHash)
		}
		if ret := Opus_opus_multistream_decoder_ctl(tls, dec, OPUS_GET_FINAL_RANGE_REQUEST, libc.VaList(va, rng)); ret != 0 {
			t.Fatalf("range CTL = %d", ret)
		}
		if got := *(*uint32)(unsafe.Pointer(rng)); got != wantRange {
			t.Fatalf("%s: range %d, want %d", name, got, wantRange)
		}
	}
	if err := scanner.Err(); err != nil {
		t.Fatal(err)
	}
}
